// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hihicwvhtbspaikfnjot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaGljd3ZodGJzcGFpa2Zuam90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTAwMjEsImV4cCI6MjA3MjA2NjAyMX0.CjIJYBP-MBAtbC4AsspvfsoIknEkKbCkRfI7RY4-uOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});